version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bookstore
    volumes:
      - mongodb_data:/data/db
      - ./mongo-scripts:/docker-entrypoint-initdb.d:ro

volumes:
  mongodb_data: